#
#Fri May 15 18:10:39 EDT 2026
components.damage=1
texture.leather_layer_1_overlay=textures/clothing/fairies/iridessa_outfit
components.dyed_color.rgb=15782174
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/fairies/iridessa_outfit
