#
#Fri May 29 21:11:39 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/ralph
nbt.display.color=16759690
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/ralph
