texture.leather_layer_2_overlay=textures/clothing/muppets/kermitpants
damage=1
nbt.display.color=1578517
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/muppets/kermitpants
