#
#Fri Apr 17 20:08:20 EDT 2026
components.damage=1
texture.leather_layer_1_overlay=textures/clothing/kbf/cm/campsnoopy
components.dyed_color.rgb=4620599
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/kbf/cm/campsnoopy
