#
#Fri May 15 18:10:39 EDT 2026
components.damage=1
texture.leather_layer_1_overlay=textures/clothing/sbl/sbl_dlpcm_v2_top
components.dyed_color.rgb=12190981
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/sbl/sbl_dlpcm_v2_top
