type=armor
items=minecraft:leather_helmet
nbt.display.color=1710618
texture.leather_layer_1=textures/clothing/uor/uorsecuritytop
texture.leather_layer_1_overlay=textures/clothing/uor/uorsecuritytop
damage=1