type=armor
items=minecraft:leather_leggings
nbt.display.color=2761507
texture.leather_layer_2=textures/clothing/uor/uorsecuritybottom
texture.leather_layer_2_overlay=textures/clothing/uor/uorsecuritybottom
damage=1