#
#Fri Apr 03 02:39:34 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/uor/characters/tigress
nbt.display.color=15789337
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/uor/characters/tigress
