damage=1
texture.leather_layer_1_overlay=textures/clothing/disneychannel/dippertop
nbt.display.color=2767696
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/disneychannel/dippertop
