type=armor
items=minecraft:leather_leggings
nbt.display.color=16185305
texture.leather_layer_2=textures/clothing/kbf/cm/campsnoopy_pants
texture.leather_layer_2_overlay=textures/clothing/kbf/cm/campsnoopy_pants
damage=1