damage=1
texture.leather_layer_1_overlay=textures/clothing/muppets/samtop
nbt.display.color=13017145
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/muppets/samtop
