damage=1
texture.leather_layer_1_overlay=textures/clothing/kbf/charliebrown
nbt.display.color=7357219
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/kbf/charliebrown
