damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/polynesian/polyqsfbtop
nbt.display.color=15451258
type=armor
items= minecraft:leather_helmet 
texture.leather_layer_1=textures/clothing/cm/polynesian/polyqsfbtop
