#
#Fri May 15 18:10:39 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/sleepingbeauty/prince_phillip_pants
damage=1
nbt.display.color=1444424
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/sleepingbeauty/prince_phillip_pants
