type=armor
items=minecraft:leather_leggings
nbt.display.color=15128496
texture.leather_layer_2=textures/clothing/potc/well_right_5_pants
texture.leather_layer_2_overlay=textures/clothing/potc/well_right_5_pants
damage=1