type=armor
items=minecraft:leather_leggings
nbt.display.color=16116694
texture.leather_layer_2=textures/clothing/potc/well_windowlady_skirt
texture.leather_layer_2_overlay=textures/clothing/potc/well_windowlady_skirt
damage=1