type=armor
items=minecraft:leather_boots
nbt.display.color=3220761
texture.leather_layer_1=textures/clothing/potc/well_right_outfit
texture.leather_layer_1_overlay=textures/clothing/potc/well_right_outfit
damage=1