#
#Fri May 29 13:47:07 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/easterbunnylegs
damage=1
nbt.display.color=13218272
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/easterbunnylegs
