type=armor
items=minecraft:leather_leggings
nbt.display.color=3704645
texture.leather_layer_2=textures/clothing/toysoldierbottom
texture.leather_layer_2_overlay=textures/clothing/toysoldierbottom
damage=1