type=armor
items=minecraft:leather_leggings
nbt.display.color=13218272
texture.leather_layer_2=textures/clothing/easterbunnylegs
texture.leather_layer_2_overlay=textures/clothing/easterbunnylegs
damage=1