type=armor
items=minecraft:leather_chestplate
nbt.display.color=16379259
texture.leather_layer_1=textures/clothing/hea/pinocchio
texture.leather_layer_1_overlay=textures/clothing/hea/pinocchio
damage=1