type=armor
items=minecraft:leather_leggings
nbt.display.color=10953740
texture.leather_layer_2=textures/clothing/hea/pinocchio_pants
texture.leather_layer_2_overlay=textures/clothing/hea/pinocchio_pants
damage=1