type=armor
items=minecraft:leather_boots
nbt.display.color=10066578
texture.leather_layer_1=textures/clothing/timothymousetop
texture.leather_layer_1_overlay=textures/clothing/timothymousetop
damage=1