type=armor
items=minecraft:leather_leggings
nbt.display.color=1709604
texture.leather_layer_2=textures/clothing/sleepingbeauty/maleficent_skirt
texture.leather_layer_2_overlay=textures/clothing/sleepingbeauty/maleficent_skirt
damage=1