texture.leather_layer_2_overlay=textures/clothing/disneychannel/eviepants
damage=1
nbt.display.color=10559789
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/disneychannel/eviepants
