damage=1
texture.leather_layer_1_overlay=textures/clothing/disneychannel/evietop
nbt.display.color=2236448
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/disneychannel/evietop
