type=armor
items=minecraft:leather_leggings
nbt.display.color=2444942
texture.leather_layer_2=textures/clothing/cm/wdwphotopass_shorts
texture.leather_layer_2_overlay=textures/clothing/cm/wdwphotopass_shorts
damage=1