type=armor
items=minecraft:leather_boots
nbt.display.color=12545081
texture.leather_layer_1=textures/clothing/hea/aladdin_outfit
texture.leather_layer_1_overlay=textures/clothing/hea/aladdin_outfit
damage=1