type=armor
items=minecraft:leather_leggings
nbt.display.color=4181732
texture.leather_layer_2=textures/clothing/hea/jasmine_pants
texture.leather_layer_2_overlay=textures/clothing/hea/jasmine_pants
damage=1