type=armor
items=minecraft:leather_leggings
nbt.display.color=10493052
texture.leather_layer_2=textures/clothing/despicableme/edith_skirt
texture.leather_layer_2_overlay=textures/clothing/despicableme/edith_skirt
damage=1