type=armor
items=minecraft:leather_boots
nbt.display.color=14872298
texture.leather_layer_1=textures/clothing/despicableme/margo
texture.leather_layer_1_overlay=textures/clothing/despicableme/margo
damage=1