type=armor
items=minecraft:leather_leggings
nbt.display.color=3288183
texture.leather_layer_2=textures/clothing/despicableme/minion_pants
texture.leather_layer_2_overlay=textures/clothing/despicableme/minion_pants
damage=1