type=armor
items=minecraft:leather_chestplate
nbt.display.color=15424768
texture.leather_layer_1=textures/clothing/despicableme/vector
texture.leather_layer_1_overlay=textures/clothing/despicableme/vector
damage=1