damage=1
texture.leather_layer_1_overlay=textures/clothing/disneychannel/mabletop
nbt.display.color=14106709
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/disneychannel/mabletop
