#
#Fri May 29 14:16:35 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/potc/jack_sparrow_outfit
nbt.display.color=1710622
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/potc/jack_sparrow_outfit
