#
#Fri Apr 03 02:39:33 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/cm/dhs/hollywoodmanbottoms
damage=1
nbt.display.color=1777190
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/cm/dhs/hollywoodmanbottoms
