damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/primetimef
nbt.display.color=14794181
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/cm/dhs/primetimef
