type=armor
items=minecraft:leather_leggings
nbt.display.color=1247777
texture.leather_layer_2=textures/clothing/sbl/chernabog_pants
texture.leather_layer_2_overlay=textures/clothing/sbl/chernabog_pants
damage=1