#
#Fri May 29 21:11:40 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/potc/well_right_5_outfit
nbt.display.color=10092826
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/potc/well_right_5_outfit
