#
#Fri May 29 13:47:08 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/potc/well_right_pants
damage=1
nbt.display.color=14602410
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/potc/well_right_pants
