#
#Fri May 29 13:47:08 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/hm/chandelier_ghost_3_skirt
damage=1
nbt.display.color=4547509
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/hm/chandelier_ghost_3_skirt
