#
#Fri Apr 17 20:08:20 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/potc/well_right_outfit
nbt.display.color=3220761
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/potc/well_right_outfit
