#
#Fri May 29 21:11:40 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/potc/captain_barbossa_outfit
nbt.display.color=1909102
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/potc/captain_barbossa_outfit
