#
#Fri Apr 17 20:08:19 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/mk/sdmt_wtp_teacup_f_top
nbt.display.color=8359773
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/cm/mk/sdmt_wtp_teacup_f_top
