texture.leather_layer_2_overlay=textures/clothing/muppets/animalpants
damage=1
nbt.display.color=2564385
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/muppets/animalpants
