texture.leather_layer_2_overlay=textures/clothing/muppets/samlegs
damage=1
nbt.display.color=6324129
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/muppets/samlegs
