damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dl/carsland/flos_m
nbt.display.color=912376
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/cm/dl/carsland/flos_m
