#
#Fri Apr 03 02:39:34 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/uor/ioa/sfa_shorts
components.damage=1
components.dyed_color.rgb=2432813
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/uor/ioa/sfa_shorts
