damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dl/carsland/rsr_shirt
nbt.display.color=15850597
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/cm/dl/carsland/rsr_shirt
