type=armor
items=minecraft:leather_boots
nbt.display.color=11171915
texture.leather_layer_1=textures/clothing/uor/characters/baby_et
texture.leather_layer_1_overlay=textures/clothing/uor/characters/baby_et
damage=1