type=armor
items=minecraft:leather_chestplate
nbt.display.color=1287270
texture.leather_layer_1=textures/clothing/uor/characters/branch
texture.leather_layer_1_overlay=textures/clothing/uor/characters/branch
damage=1