type=armor
items=minecraft:leather_boots
nbt.display.color=3902117
texture.leather_layer_1=textures/clothing/uor/characters/branch
texture.leather_layer_1_overlay=textures/clothing/uor/characters/branch
damage=1