type=armor
items=minecraft:leather_boots
nbt.display.color=14012631
texture.leather_layer_1=textures/clothing/uor/characters/kingjulien
texture.leather_layer_1_overlay=textures/clothing/uor/characters/kingjulien
damage=1