type=armor
items=minecraft:leather_boots
nbt.display.color=16747274
texture.leather_layer_1=textures/clothing/uor/characters/lorax
texture.leather_layer_1_overlay=textures/clothing/uor/characters/lorax
damage=1