type=armor
items=minecraft:leather_leggings
nbt.display.color=16747274
texture.leather_layer_2=textures/clothing/uor/characters/lorax_pants
texture.leather_layer_2_overlay=textures/clothing/uor/characters/lorax_pants
damage=1