type=armor
items=minecraft:leather_leggings
nbt.display.color=14193944
texture.leather_layer_2=textures/clothing/uor/characters/po_pants
texture.leather_layer_2_overlay=textures/clothing/uor/characters/po_pants
damage=1