type=armor
items=minecraft:leather_boots
nbt.display.color=13086586
texture.leather_layer_1=textures/clothing/uor/characters/po
texture.leather_layer_1_overlay=textures/clothing/uor/characters/po
damage=1