type=armor
items=minecraft:leather_boots
nbt.display.color=2695188
texture.leather_layer_1=textures/clothing/uor/characters/puss
texture.leather_layer_1_overlay=textures/clothing/uor/characters/puss
damage=1