type=armor
items=minecraft:leather_boots
nbt.display.color=2891570
texture.leather_layer_1=textures/clothing/uor/characters/rosita
texture.leather_layer_1_overlay=textures/clothing/uor/characters/rosita
damage=1