type=armor
items=minecraft:leather_leggings
nbt.display.color=2666410
texture.leather_layer_2=textures/clothing/uor/characters/squidward_pants
texture.leather_layer_2_overlay=textures/clothing/uor/characters/squidward_pants
damage=1