damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/oscartop
nbt.display.color=13816534
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/cm/dhs/oscartop
