#
#Fri May 29 21:31:38 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/sbl/sbl_dlpcm_v1_outfit
nbt.display.color=11535621
type=armor
items= minecraft:leather_helmet 
texture.leather_layer_1=textures/clothing/sbl/sbl_dlpcm_v1_outfit
