#
#Fri May 29 21:31:38 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/uor/ioa/sfa_shorts
damage=1
nbt.display.color=2432813
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/uor/ioa/sfa_shorts
