damage=1
texture.leather_layer_1_overlay=textures/clothing/hea/evil_hag_outfit
nbt.display.color=592668
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/hea/evil_hag_outfit
