damage=1
texture.leather_layer_1_overlay=textures/clothing/hea/prince_florian_outfit
nbt.display.color=526344
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/hea/prince_florian_outfit
