type=armor
items=minecraft:leather_leggings
nbt.display.color=12918302
texture.leather_layer_2=textures/clothing/cm/polynesian/polyconciergefemalebottom
texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polyconciergefemalebottom
damage=1