type=armor
items=minecraft:leather_helmet
nbt.display.color=15451258
texture.leather_layer_1=textures/clothing/cm/polynesian/polyqsfbtop
texture.leather_layer_1_overlay=textures/clothing/cm/polynesian/polyqsfbtop
damage=1