type=armor
items=minecraft:leather_leggings
nbt.display.color=14836580
texture.leather_layer_2=textures/clothing/cm/polynesian/polyserver2bottom
texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polyserver2bottom
damage=1