type=armor
items=minecraft:leather_leggings
nbt.display.color=13551540
texture.leather_layer_2=textures/clothing/cm/polynesian/polymerchmalebottom
texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polymerchmalebottom
damage=1