type=armor
items=minecraft:leather_leggings
nbt.display.color=163541
texture.leather_layer_2=textures/clothing/cm/polynesian/polytowerpants
texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polytowerpants
damage=1