type=armor
items=minecraft:leather_leggings
nbt.display.color=12371832
texture.leather_layer_2=textures/clothing/cm/polynesian/polymerchfemalebottom
texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polymerchfemalebottom
damage=1