type=armor
items=minecraft:leather_chestplate
nbt.display.color=10013786
texture.leather_layer_1=textures/clothing/cm/polynesian/polyqsfbtop
texture.leather_layer_1_overlay=textures/clothing/cm/polynesian/polyqsfbtop
damage=1