type=armor
items=minecraft:leather_chestplate
nbt.display.color=14836580
texture.leather_layer_1=textures/clothing/cm/polynesian/polyserver2skin
texture.leather_layer_1_overlay=textures/clothing/cm/polynesian/polyserver2skin
damage=1