type=armor
items=minecraft:leather_leggings
nbt.display.color=12535571
texture.leather_layer_2=textures/clothing/cm/polynesian/polyqsfbpants
texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polyqsfbpants
damage=1