type=armor
items=minecraft:leather_leggings
nbt.display.color=132503
texture.leather_layer_2=textures/clothing/cm/dl/dl_peoplemover_pants
texture.leather_layer_2_overlay=textures/clothing/cm/dl/dl_peoplemover_pants
damage=1