type=armor
items=minecraft:leather_chestplate
nbt.display.color=8052479
texture.leather_layer_1=textures/clothing/cm/dl/dlrphotopasstop
texture.leather_layer_1_overlay=textures/clothing/cm/dl/dlrphotopasstop
damage=1