type=armor
items=minecraft:leather_chestplate
nbt.display.color=1710622
texture.leather_layer_1=textures/clothing/potc/jack_sparrow_outfit
texture.leather_layer_1_overlay=textures/clothing/potc/jack_sparrow_outfit
damage=1