texture.leather_layer_2_overlay=textures/clothing/muppets/beakerpants
damage=1
nbt.display.color=9735493
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/muppets/beakerpants
