damage=1
texture.leather_layer_1_overlay=textures/clothing/muppets/drteethtop
nbt.display.color=11705041
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/muppets/drteethtop
