texture.leather_layer_2_overlay=textures/clothing/muppets/scooterpants
damage=1
nbt.display.color=411014
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/muppets/scooterpants
