type=armor
items=minecraft:leather_leggings
nbt.display.color=9735493
texture.leather_layer_2=textures/clothing/muppets/beakerpants
texture.leather_layer_2_overlay=textures/clothing/muppets/beakerpants
damage=1