type=armor
items=minecraft:leather_leggings
nbt.display.color=2170912
texture.leather_layer_2=textures/clothing/muppets/drteethpants
texture.leather_layer_2_overlay=textures/clothing/muppets/drteethpants
damage=1