type=armor
items=minecraft:leather_chestplate
nbt.display.color=11705041
texture.leather_layer_1=textures/clothing/muppets/drteethtop
texture.leather_layer_1_overlay=textures/clothing/muppets/drteethtop
damage=1