type=armor
items=minecraft:leather_leggings
nbt.display.color=14455106
texture.leather_layer_2=textures/clothing/muppets/fozzielegs
texture.leather_layer_2_overlay=textures/clothing/muppets/fozzielegs
damage=1