type=armor
items=minecraft:leather_chestplate
nbt.display.color=14455106
texture.leather_layer_1=textures/clothing/muppets/fozzietop
texture.leather_layer_1_overlay=textures/clothing/muppets/fozzietop
damage=1