type=armor
items=minecraft:leather_leggings
nbt.display.color=14327087
texture.leather_layer_2=textures/clothing/muppets/gonzobottom
texture.leather_layer_2_overlay=textures/clothing/muppets/gonzobottom
damage=1