type=armor
items=minecraft:leather_boots
nbt.display.color=2823692
texture.leather_layer_1=textures/clothing/muppets/janicetop
texture.leather_layer_1_overlay=textures/clothing/muppets/janicetop
damage=1