type=armor
items=minecraft:leather_chestplate
nbt.display.color=16229598
texture.leather_layer_1=textures/clothing/muppets/janicetop
texture.leather_layer_1_overlay=textures/clothing/muppets/janicetop
damage=1