type=armor
items=minecraft:leather_leggings
nbt.display.color=1315384
texture.leather_layer_2=textures/clothing/muppets/janicepants
texture.leather_layer_2_overlay=textures/clothing/muppets/janicepants
damage=1