type=armor
items=minecraft:leather_boots
nbt.display.color=3942679
texture.leather_layer_1=textures/clothing/muppets/kermittop
texture.leather_layer_1_overlay=textures/clothing/muppets/kermittop
damage=1