type=armor
items=minecraft:leather_leggings
nbt.display.color=1578517
texture.leather_layer_2=textures/clothing/muppets/kermitpants
texture.leather_layer_2_overlay=textures/clothing/muppets/kermitpants
damage=1