type=armor
items=minecraft:leather_chestplate
nbt.display.color=9587475
texture.leather_layer_1=textures/clothing/muppets/kermittop
texture.leather_layer_1_overlay=textures/clothing/muppets/kermittop
damage=1