type=armor
items=minecraft:leather_chestplate
nbt.display.color=8983572
texture.leather_layer_1=textures/clothing/muppets/lipstop
texture.leather_layer_1_overlay=textures/clothing/muppets/lipstop
damage=1