type=armor
items=minecraft:leather_chestplate
nbt.display.color=2171167
texture.leather_layer_1=textures/clothing/muppets/piggytop
texture.leather_layer_1_overlay=textures/clothing/muppets/piggytop
damage=1