type=armor
items=minecraft:leather_leggings
nbt.display.color=2171167
texture.leather_layer_2=textures/clothing/muppets/piggypants
texture.leather_layer_2_overlay=textures/clothing/muppets/piggypants
damage=1