type=armor
items=minecraft:leather_leggings
nbt.display.color=411014
texture.leather_layer_2=textures/clothing/muppets/scooterpants
texture.leather_layer_2_overlay=textures/clothing/muppets/scooterpants
damage=1