type=armor
items=minecraft:leather_boots
nbt.display.color=11289369
texture.leather_layer_1=textures/clothing/muppets/scootertop
texture.leather_layer_1_overlay=textures/clothing/muppets/scootertop
damage=1