type=armor
items=minecraft:leather_leggings
nbt.display.color=2368548
texture.leather_layer_2=textures/clothing/muppets/statlerpants
texture.leather_layer_2_overlay=textures/clothing/muppets/statlerpants
damage=1