type=armor
items=minecraft:leather_chestplate
nbt.display.color=6195048
texture.leather_layer_1=textures/clothing/muppets/statlertop
texture.leather_layer_1_overlay=textures/clothing/muppets/statlertop
damage=1