type=armor
items=minecraft:leather_boots
nbt.display.color=3746072
texture.leather_layer_1=textures/clothing/muppets/sweetumstop
texture.leather_layer_1_overlay=textures/clothing/muppets/sweetumstop
damage=1