type=armor
items=minecraft:leather_chestplate
nbt.display.color=10319958
texture.leather_layer_1=textures/clothing/muppets/sweetumstop
texture.leather_layer_1_overlay=textures/clothing/muppets/sweetumstop
damage=1