type=armor
items=minecraft:leather_leggings
nbt.display.color=10319958
texture.leather_layer_2=textures/clothing/muppets/sweetumslegs
texture.leather_layer_2_overlay=textures/clothing/muppets/sweetumslegs
damage=1