type=armor
items=minecraft:leather_boots
nbt.display.color=5998508
texture.leather_layer_1=textures/clothing/muppets/deadlytop
texture.leather_layer_1_overlay=textures/clothing/muppets/deadlytop
damage=1