type=armor
items=minecraft:leather_leggings
nbt.display.color=3158321
texture.leather_layer_2=textures/clothing/muppets/deadlypants
texture.leather_layer_2_overlay=textures/clothing/muppets/deadlypants
damage=1