type=armor
items=minecraft:leather_chestplate
nbt.display.color=3943760
texture.leather_layer_1=textures/clothing/muppets/waldorftop
texture.leather_layer_1_overlay=textures/clothing/muppets/waldorftop
damage=1