type=armor
items=minecraft:leather_leggings
nbt.display.color=9525808
texture.leather_layer_2=textures/clothing/muppets/zootpants
texture.leather_layer_2_overlay=textures/clothing/muppets/zootpants
damage=1