#
#Fri Apr 17 20:08:19 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/captain_pants
damage=1
nbt.display.color=15329768
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/captain_pants
