type=armor
items=minecraft:leather_leggings
nbt.display.color=1845578
texture.leather_layer_2=textures/clothing/hm/chandelier_ghost_1_pants
texture.leather_layer_2_overlay=textures/clothing/hm/chandelier_ghost_1_pants
damage=1