type=armor
items=minecraft:leather_boots
nbt.display.color=4547509
texture.leather_layer_1=textures/clothing/hm/chandelier_ghost_3_outfit
texture.leather_layer_1_overlay=textures/clothing/hm/chandelier_ghost_3_outfit
damage=1