type=armor
items=minecraft:leather_leggings
nbt.display.color=2245729
texture.leather_layer_2=textures/clothing/hm/gy_ghost_5_pants
texture.leather_layer_2_overlay=textures/clothing/hm/gy_ghost_5_pants
damage=1