type=armor
items=minecraft:leather_leggings
nbt.display.color=1667458
texture.leather_layer_2=textures/clothing/hm/gy_ghost_6_pants
texture.leather_layer_2_overlay=textures/clothing/hm/gy_ghost_6_pants
damage=1