type=armor
items=minecraft:leather_chestplate
nbt.display.color=4088711
texture.leather_layer_1=textures/clothing/hm/gy_ghost_7_outfit
texture.leather_layer_1_overlay=textures/clothing/hm/gy_ghost_7_outfit
damage=1