type=armor
items=minecraft:leather_leggings
nbt.display.color=5146524
texture.leather_layer_2=textures/clothing/hm/gy_ghost_8_pants
texture.leather_layer_2_overlay=textures/clothing/hm/gy_ghost_8_pants
damage=1