type=armor
items=minecraft:leather_leggings
nbt.display.color=3048647
texture.leather_layer_2=textures/clothing/hm/gy_ghost_11_skirt
texture.leather_layer_2_overlay=textures/clothing/hm/gy_ghost_11_skirt
damage=1