type=armor
items=minecraft:leather_leggings
nbt.display.color=2168077
texture.leather_layer_2=textures/clothing/hm/gy_guy_pants
texture.leather_layer_2_overlay=textures/clothing/hm/gy_guy_pants
damage=1