type=armor
items=minecraft:leather_boots
nbt.display.color=3048647
texture.leather_layer_1=textures/clothing/hm/gy_ghost_11_outfit
texture.leather_layer_1_overlay=textures/clothing/hm/gy_ghost_11_outfit
damage=1