type=armor
items=minecraft:leather_boots
nbt.display.color=5146524
texture.leather_layer_1=textures/clothing/hm/gy_ghost_8_outfit
texture.leather_layer_1_overlay=textures/clothing/hm/gy_ghost_8_outfit
damage=1