#
#Fri May 29 21:31:38 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/tlm/ariel_show_outfit
nbt.display.color=1475848
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/tlm/ariel_show_outfit
