texture.leather_layer_2_overlay=textures/clothing/fairies/fawn_skirt
damage=1
nbt.display.color=9064973
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/fairies/fawn_skirt
