texture.leather_layer_2_overlay=textures/clothing/kbf/franklin_shorts
damage=1
nbt.display.color=3827915
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/kbf/franklin_shorts
