texture.leather_layer_2_overlay=textures/clothing/insideout/joy_skirt
damage=1
nbt.display.color=10875450
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/insideout/joy_skirt
