damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/transportation/ms_vehicle_driver
nbt.display.color=927079
type=armor
items= minecraft:leather_helmet 
texture.leather_layer_1=textures/clothing/cm/transportation/ms_vehicle_driver
