#
#Fri Apr 17 20:08:19 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/hhn/tangina_barrons_skirt
damage=1
nbt.display.color=6850398
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/hhn/tangina_barrons_skirt
