#
#Fri May 29 14:16:35 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/potc/captain_barbossa_pants
damage=1
nbt.display.color=14404785
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/potc/captain_barbossa_pants
