texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polyqsfbpants
damage=1
nbt.display.color=12535571
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/cm/polynesian/polyqsfbpants
