#
#Fri May 15 18:10:38 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/strawberry
nbt.display.color=8915971
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/cm/dhs/strawberry
