damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/trolleyf
nbt.display.color=8851513
type=armor
items= minecraft:leather_helmet 
texture.leather_layer_1=textures/clothing/cm/dhs/trolleyf
