#
#Fri May 29 14:16:35 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/hm/gy_ghost_9_outfit
nbt.display.color=4937387
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/hm/gy_ghost_9_outfit
