type=armor
items=minecraft:leather_chestplate
nbt.display.color=15396341
texture.leather_layer_1=textures/clothing/insideout/anger
texture.leather_layer_1_overlay=textures/clothing/insideout/anger
damage=1