type=armor
items=minecraft:leather_boots
nbt.display.color=5906308
texture.leather_layer_1=textures/clothing/insideout/disgust
texture.leather_layer_1_overlay=textures/clothing/insideout/disgust
damage=1