type=armor
items=minecraft:leather_chestplate
nbt.display.color=15656947
texture.leather_layer_1=textures/clothing/insideout/fear
texture.leather_layer_1_overlay=textures/clothing/insideout/fear
damage=1