damage=1
texture.leather_layer_1_overlay=textures/clothing/potc/captain_barbossa_outfit
nbt.display.color=986636
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/potc/captain_barbossa_outfit
