type=armor
items=minecraft:leather_leggings
nbt.display.color=15695526
texture.leather_layer_2=textures/clothing/disneychannel/allisonpants
texture.leather_layer_2_overlay=textures/clothing/disneychannel/allisonpants
damage=1