type=armor
items=minecraft:leather_leggings
nbt.display.color=3224114
texture.leather_layer_2=textures/clothing/disneychannel/bertrampants
texture.leather_layer_2_overlay=textures/clothing/disneychannel/bertrampants
damage=1