type=armor
items=minecraft:leather_chestplate
nbt.display.color=5855061
texture.leather_layer_1=textures/clothing/disneychannel/bertramtop
texture.leather_layer_1_overlay=textures/clothing/disneychannel/bertramtop
damage=1