type=armor
items=minecraft:leather_chestplate
nbt.display.color=2767696
texture.leather_layer_1=textures/clothing/disneychannel/dippertop
texture.leather_layer_1_overlay=textures/clothing/disneychannel/dippertop
damage=1