type=armor
items=minecraft:leather_leggings
nbt.display.color=6251622
texture.leather_layer_2=textures/clothing/disneychannel/dipperpants
texture.leather_layer_2_overlay=textures/clothing/disneychannel/dipperpants
damage=1