type=armor
items=minecraft:leather_boots
nbt.display.color=3158064
texture.leather_layer_1=textures/clothing/disneychannel/dippertop
texture.leather_layer_1_overlay=textures/clothing/disneychannel/dippertop
damage=1