type=armor
items=minecraft:leather_leggings
nbt.display.color=10330993
texture.leather_layer_2=textures/clothing/disneychannel/kimpossiblebottom
texture.leather_layer_2_overlay=textures/clothing/disneychannel/kimpossiblebottom
damage=1