type=armor
items=minecraft:leather_chestplate
nbt.display.color=14106709
texture.leather_layer_1=textures/clothing/disneychannel/mabletop
texture.leather_layer_1_overlay=textures/clothing/disneychannel/mabletop
damage=1