type=armor
items=minecraft:leather_leggings
nbt.display.color=8478868
texture.leather_layer_2=textures/clothing/disneychannel/mablepants
texture.leather_layer_2_overlay=textures/clothing/disneychannel/mablepants
damage=1