type=armor
items=minecraft:leather_boots
nbt.display.color=3876706
texture.leather_layer_1=textures/clothing/disneychannel/maltop
texture.leather_layer_1_overlay=textures/clothing/disneychannel/maltop
damage=1