type=armor
items=minecraft:leather_chestplate
nbt.display.color=6179699
texture.leather_layer_1=textures/clothing/disneychannel/maltop
texture.leather_layer_1_overlay=textures/clothing/disneychannel/maltop
damage=1