type=armor
items=minecraft:leather_leggings
nbt.display.color=2829099
texture.leather_layer_2=textures/clothing/disneychannel/mrmosbypants
texture.leather_layer_2_overlay=textures/clothing/disneychannel/mrmosbypants
damage=1