type=armor
items=minecraft:leather_boots
nbt.display.color=214417
texture.leather_layer_1=textures/clothing/disneychannel/phineas
texture.leather_layer_1_overlay=textures/clothing/disneychannel/phineas
damage=1