type=armor
items=minecraft:leather_chestplate
nbt.display.color=16090624
texture.leather_layer_1=textures/clothing/disneychannel/phineas
texture.leather_layer_1_overlay=textures/clothing/disneychannel/phineas
damage=1