type=armor
items=minecraft:leather_leggings
nbt.display.color=13243926
texture.leather_layer_2=textures/clothing/disneychannel/wildcats_shorts
texture.leather_layer_2_overlay=textures/clothing/disneychannel/wildcats_shorts
damage=1