type=armor
items=minecraft:leather_leggings
nbt.display.color=14688058
texture.leather_layer_2=textures/clothing/sleepingbeauty/flora_skirt
texture.leather_layer_2_overlay=textures/clothing/sleepingbeauty/flora_skirt
damage=1