type=armor
items=minecraft:leather_boots
nbt.display.color=14688058
texture.leather_layer_1=textures/clothing/sleepingbeauty/flora_outfit
texture.leather_layer_1_overlay=textures/clothing/sleepingbeauty/flora_outfit
damage=1