type=armor
items=minecraft:leather_chestplate
nbt.display.color=6083302
texture.leather_layer_1=textures/clothing/sleepingbeauty/merryweather_outfit
texture.leather_layer_1_overlay=textures/clothing/sleepingbeauty/merryweather_outfit
damage=1