type=armor
items=minecraft:leather_leggings
nbt.display.color=6083302
texture.leather_layer_2=textures/clothing/sleepingbeauty/merryweather_skirt
texture.leather_layer_2_overlay=textures/clothing/sleepingbeauty/merryweather_skirt
damage=1