damage=1
texture.leather_layer_1_overlay=textures/clothing/timothymousetop
nbt.display.color=13314618
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/timothymousetop
