#
#Fri May 29 21:11:40 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/kbf/lucy_skirt
damage=1
nbt.display.color=6066400
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/kbf/lucy_skirt
