#
#Fri May 29 13:47:08 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/kbf/schroeder_shorts
damage=1
nbt.display.color=2503872
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/kbf/schroeder_shorts
