#
#Fri May 15 18:10:39 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/hm/chandelier_ghost_2_pants
damage=1
nbt.display.color=8891218
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/hm/chandelier_ghost_2_pants
