#
#Fri Apr 17 20:08:19 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/hm/chandelier_ghost_1_pants
damage=1
nbt.display.color=1845578
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/hm/chandelier_ghost_1_pants
