texture.leather_layer_2_overlay=textures/clothing/kbf/boysenbear_pants
damage=1
nbt.display.color=3095734
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/kbf/boysenbear_pants
