#
#Fri Apr 17 20:08:19 EDT 2026
components.damage=1
texture.leather_layer_1_overlay=textures/clothing/galaxysedge/bek
components.dyed_color.rgb=2108983
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/galaxysedge/bek
