type=armor
items=minecraft:leather_chestplate
nbt.display.color=5803446
texture.leather_layer_1=textures/clothing/fairies/bluefairy_outfit
texture.leather_layer_1_overlay=textures/clothing/fairies/bluefairy_outfit
damage=1