type=armor
items=minecraft:leather_chestplate
nbt.display.color=15772446
texture.leather_layer_1=textures/clothing/fairies/fawn_outfit
texture.leather_layer_1_overlay=textures/clothing/fairies/fawn_outfit
damage=1