type=armor
items=minecraft:leather_boots
nbt.display.color=8079370
texture.leather_layer_1=textures/clothing/fairies/rosetta_outfit
texture.leather_layer_1_overlay=textures/clothing/fairies/rosetta_outfit
damage=1