type=armor
items=minecraft:leather_leggings
nbt.display.color=4826588
texture.leather_layer_2=textures/clothing/fairies/silvermist_skirt
texture.leather_layer_2_overlay=textures/clothing/fairies/silvermist_skirt
damage=1