type=armor
items=minecraft:leather_leggings
nbt.display.color=9246834
texture.leather_layer_2=textures/clothing/fairies/vidia_skirt
texture.leather_layer_2_overlay=textures/clothing/fairies/vidia_skirt
damage=1