#
#Fri May 29 21:31:37 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/despicableme/edith_skirt
damage=1
nbt.display.color=10493052
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/despicableme/edith_skirt
