#
#Fri May 29 14:16:34 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/despicableme/vector_pants
damage=1
nbt.display.color=15424768
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/despicableme/vector_pants
