type=armor
items=minecraft:leather_boots
nbt.display.color=4020093
texture.leather_layer_1=textures/clothing/tlm/ariel_human_outfit
texture.leather_layer_1_overlay=textures/clothing/tlm/ariel_human_outfit
damage=1