type=armor
items=minecraft:leather_chestplate
nbt.display.color=14668489
texture.leather_layer_1=textures/clothing/tlm/eric_outfit
texture.leather_layer_1_overlay=textures/clothing/tlm/eric_outfit
damage=1