type=armor
items=minecraft:leather_chestplate
nbt.display.color=13410160
texture.leather_layer_1=textures/clothing/tlm/melody_outfit
texture.leather_layer_1_overlay=textures/clothing/tlm/melody_outfit
damage=1