type=armor
items=minecraft:leather_leggings
nbt.display.color=1383802
texture.leather_layer_2=textures/clothing/tlm/prince_eric_pants
texture.leather_layer_2_overlay=textures/clothing/tlm/prince_eric_pants
damage=1