type=armor
items=minecraft:leather_boots
nbt.display.color=1119252
texture.leather_layer_1=textures/clothing/tlm/prince_eric_outfit
texture.leather_layer_1_overlay=textures/clothing/tlm/prince_eric_outfit
damage=1