damage=1
texture.leather_layer_1_overlay=textures/clothing/timothymousetop
nbt.display.color=10066578
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/timothymousetop
