#
#Fri May 29 21:31:37 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/despicableme/edith
nbt.display.color=15851500
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/despicableme/edith
