#
#Fri Apr 03 02:39:34 EDT 2026
components.damage=1
texture.leather_layer_1_overlay=textures/clothing/potc/jack_sparrow_outfit
components.dyed_color.rgb=3741184
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/potc/jack_sparrow_outfit
