#
#Fri May 29 13:47:09 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/world_showcase/japan/takumitei_seater_skirt
damage=1
nbt.display.color=15984832
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/world_showcase/japan/takumitei_seater_skirt
