type=armor
items=minecraft:leather_helmet
nbt.display.color=10361135
texture.leather_layer_1=textures/clothing/cm/dhs/dhsecholakegreenshortsleevetop
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/dhsecholakegreenshortsleevetop
damage=1