type=armor
items=minecraft:leather_helmet
nbt.display.color=13090992
texture.leather_layer_1=textures/clothing/cm/dhs/dhsecholakeshortsleevetop
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/dhsecholakeshortsleevetop
damage=1