type=armor
items=minecraft:leather_chestplate
nbt.display.color=7390651
texture.leather_layer_1=textures/clothing/cm/dhs/dhsecholakegreenshortsleevetop
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/dhsecholakegreenshortsleevetop
damage=1