type=armor
items=minecraft:leather_leggings
nbt.display.color=2175830
texture.leather_layer_2=textures/clothing/cm/dhs/rrcjeans
texture.leather_layer_2_overlay=textures/clothing/cm/dhs/rrcjeans
damage=1