type=armor
items=minecraft:leather_leggings
nbt.display.color=2301727
texture.leather_layer_2=textures/clothing/cm/dhs/rrcpants
texture.leather_layer_2_overlay=textures/clothing/cm/dhs/rrcpants
damage=1