type=armor
items=minecraft:leather_leggings
nbt.display.color=473418
texture.leather_layer_2=textures/clothing/cm/dhs/strawberry_skirt
texture.leather_layer_2_overlay=textures/clothing/cm/dhs/strawberry_skirt
damage=1