type=armor
items=minecraft:leather_chestplate
nbt.display.color=8915971
texture.leather_layer_1=textures/clothing/cm/dhs/strawberry
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/strawberry
damage=1