type=armor
items=minecraft:leather_helmet
nbt.display.color=8851513
texture.leather_layer_1=textures/clothing/cm/dhs/trolleyf
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/trolleyf
damage=1