damage=1
texture.leather_layer_1_overlay=textures/clothing/disneychannel/dippertop
nbt.display.color=3158064
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/disneychannel/dippertop
