damage=1
texture.leather_layer_1_overlay=textures/clothing/disneychannel/mrmosbytop
nbt.display.color=9929310
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/disneychannel/mrmosbytop
