#
#Fri Apr 03 02:39:34 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/hm/gy_ghost_15_pants
damage=1
nbt.display.color=2179742
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/hm/gy_ghost_15_pants
