#
#Fri May 29 21:31:38 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/rey_lj_pants
damage=1
nbt.display.color=5196612
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/rey_lj_pants
