#
#Fri Apr 17 20:08:19 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/hm/chandelier_ghost_1_top
nbt.display.color=1845578
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/hm/chandelier_ghost_1_top
