type=armor
items=minecraft:leather_boots
nbt.display.color=2167812
texture.leather_layer_1=textures/clothing/hea/dwarf_sneezy_outfit
texture.leather_layer_1_overlay=textures/clothing/hea/dwarf_sneezy_outfit
damage=1