type=armor
items=minecraft:leather_leggings
nbt.display.color=6471633
texture.leather_layer_2=textures/clothing/hea/dwarf_happy_pants
texture.leather_layer_2_overlay=textures/clothing/hea/dwarf_happy_pants
damage=1