type=armor
items=minecraft:leather_leggings
nbt.display.color=3754520
texture.leather_layer_2=textures/clothing/hea/dwarf_dopey_pants
texture.leather_layer_2_overlay=textures/clothing/hea/dwarf_dopey_pants
damage=1