type=armor
items=minecraft:leather_boots
nbt.display.color=7996442
texture.leather_layer_1=textures/clothing/hea/dwarf_grumpy_outfit
texture.leather_layer_1_overlay=textures/clothing/hea/dwarf_grumpy_outfit
damage=1