type=armor
items=minecraft:leather_boots
nbt.display.color=8001035
texture.leather_layer_1=textures/clothing/hea/dwarf_doc_outfit
texture.leather_layer_1_overlay=textures/clothing/hea/dwarf_doc_outfit
damage=1