type=armor
items=minecraft:leather_boots
nbt.display.color=13748060
texture.leather_layer_1=textures/clothing/hea/dwarf_bashful_outfit
texture.leather_layer_1_overlay=textures/clothing/hea/dwarf_bashful_outfit
damage=1