type=armor
items=minecraft:leather_chestplate
nbt.display.color=5508453
texture.leather_layer_1=textures/clothing/hea/evil_queen_outfit
texture.leather_layer_1_overlay=textures/clothing/hea/evil_queen_outfit
damage=1