type=armor
items=minecraft:leather_leggings
nbt.display.color=526344
texture.leather_layer_2=textures/clothing/hea/prince_florian_pants
texture.leather_layer_2_overlay=textures/clothing/hea/prince_florian_pants
damage=1