damage=1
texture.leather_layer_1_overlay=textures/clothing/muppets/floydtop
nbt.display.color=11803161
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/muppets/floydtop
