damage=1
texture.leather_layer_1_overlay=textures/clothing/muppets/deadlytop
nbt.display.color=11578794
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/muppets/deadlytop
