damage=1
texture.leather_layer_1_overlay=textures/clothing/hea/dwarf_grumpy_outfit
nbt.display.color=7996442
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/hea/dwarf_grumpy_outfit
