texture.leather_layer_2_overlay=textures/clothing/hea/snow_white_skirt
damage=1
nbt.display.color=16763696
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/hea/snow_white_skirt
