#
#Fri May 29 13:47:08 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/sleepingbeauty/merryweather_skirt
damage=1
nbt.display.color=6083302
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/sleepingbeauty/merryweather_skirt
