#
#Fri Apr 03 02:39:34 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/hm/gy_ghost_10_pants
components.damage=1
components.dyed_color.rgb=4147343
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/hm/gy_ghost_10_pants
