#
#Fri May 29 21:11:39 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polymerchfemalebottom
damage=1
nbt.display.color=12371832
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/cm/polynesian/polymerchfemalebottom
