#
#Fri May 29 14:16:34 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/cm/polynesian/polytowerpants
damage=1
nbt.display.color=163541
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/cm/polynesian/polytowerpants
