texture.leather_layer_2_overlay=textures/clothing/disneychannel/dipperpants
damage=1
nbt.display.color=6251622
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/disneychannel/dipperpants
