texture.leather_layer_2_overlay=textures/clothing/disneychannel/kimpossiblebottom
damage=1
nbt.display.color=10330993
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/disneychannel/kimpossiblebottom
