damage=1
texture.leather_layer_1_overlay=textures/clothing/disneychannel/kimpossibletop
nbt.display.color=3881787
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/disneychannel/kimpossibletop
