#
#Fri May 29 13:47:07 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dl/dl_peoplemover_jacket
nbt.display.color=132503
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/cm/dl/dl_peoplemover_jacket
