#
#Fri Apr 03 02:39:34 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/tlm/eric_pants
components.damage=1
components.dyed_color.rgb=6909050
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/tlm/eric_pants
