#
#Fri May 29 13:47:07 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/hollywoodmantop
nbt.display.color=13621227
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/cm/dhs/hollywoodmantop
