texture.leather_layer_2_overlay=textures/clothing/hea/dwarf_happy_pants
damage=1
nbt.display.color=6471633
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/hea/dwarf_happy_pants
