damage=1
texture.leather_layer_1_overlay=textures/clothing/epcot_skins/wol_f
nbt.display.color=12260988
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/epcot_skins/wol_f
