#
#Fri Apr 03 02:39:33 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/dhs/abctop
nbt.display.color=2170910
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/cm/dhs/abctop
