type=armor
items=minecraft:leather_chestplate
nbt.display.color=1460442
texture.leather_layer_1=textures/clothing/cm/mk/bigtop_blueapron
texture.leather_layer_1_overlay=textures/clothing/cm/mk/bigtop_blueapron
damage=1