type=armor
items=minecraft:leather_leggings
nbt.display.color=15373847
texture.leather_layer_2=textures/clothing/cm/mk/tikiyellowpants
texture.leather_layer_2_overlay=textures/clothing/cm/mk/tikiyellowpants
damage=1