type=armor
items=minecraft:leather_chestplate
nbt.display.color=1202292
texture.leather_layer_1=textures/clothing/cm/mk/tikibluetop
texture.leather_layer_1_overlay=textures/clothing/cm/mk/tikibluetop
damage=1