type=armor
items=minecraft:leather_helmet
nbt.display.color=15333111
texture.leather_layer_1=textures/clothing/cm/dl/carsland/flos_m
texture.leather_layer_1_overlay=textures/clothing/cm/dl/carsland/flos_m
damage=1