type=armor
items=minecraft:leather_boots
nbt.display.color=1445133
texture.leather_layer_1=textures/clothing/cm/dl/carsland/flos_m
texture.leather_layer_1_overlay=textures/clothing/cm/dl/carsland/flos_m
damage=1