type=armor
items=minecraft:leather_leggings
nbt.display.color=1766399
texture.leather_layer_2=textures/clothing/cm/dl/carsland/flos_skirt
texture.leather_layer_2_overlay=textures/clothing/cm/dl/carsland/flos_skirt
damage=1