type=armor
items=minecraft:leather_chestplate
nbt.display.color=16448239
texture.leather_layer_1=textures/clothing/cm/dl/carsland/maters_shirt
texture.leather_layer_1_overlay=textures/clothing/cm/dl/carsland/maters_shirt
damage=1