type=armor
items=minecraft:leather_helmet
nbt.display.color=11265015
texture.leather_layer_1=textures/clothing/cm/dl/carsland/maters_shirt
texture.leather_layer_1_overlay=textures/clothing/cm/dl/carsland/maters_shirt
damage=1