type=armor
items=minecraft:leather_leggings
nbt.display.color=15863053
texture.leather_layer_2=textures/clothing/cm/dl/carsland/rsr_pants
texture.leather_layer_2_overlay=textures/clothing/cm/dl/carsland/rsr_pants
damage=1