type=armor
items=minecraft:leather_helmet
nbt.display.color=15863053
texture.leather_layer_1=textures/clothing/cm/dl/carsland/rsr_shirt
texture.leather_layer_1_overlay=textures/clothing/cm/dl/carsland/rsr_shirt
damage=1