damage=1
texture.leather_layer_1_overlay=textures/clothing/disneychannel/maltop
nbt.display.color=6179699
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/disneychannel/maltop
