damage=1
texture.leather_layer_1_overlay=textures/clothing/disneychannel/zedtop
nbt.display.color=2445627
type=armor
items= minecraft:leather_chestplate 
texture.leather_layer_1=textures/clothing/disneychannel/zedtop
