#
#Fri May 29 21:31:37 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/fairies/iridessa_outfit
nbt.display.color=15782174
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/fairies/iridessa_outfit
