texture.leather_layer_2_overlay=textures/clothing/potc/well_left_1_pants
damage=1
nbt.display.color=13944478
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/potc/well_left_1_pants
