#
#Fri Apr 03 02:39:33 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/despicableme/margo
nbt.display.color=14872298
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/despicableme/margo
