damage=1
texture.leather_layer_1_overlay=textures/clothing/muppets/janicetop
nbt.display.color=2823692
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/muppets/janicetop
