damage=1
texture.leather_layer_1_overlay=textures/clothing/muppets/cheftop
nbt.display.color=5388835
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/muppets/cheftop
