damage=1
texture.leather_layer_1_overlay=textures/clothing/muppets/gonzotop
nbt.display.color=14327087
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/muppets/gonzotop
