texture.leather_layer_2_overlay=textures/clothing/muppets/janicepants
damage=1
nbt.display.color=1315384
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/muppets/janicepants
