damage=1
texture.leather_layer_1_overlay=textures/clothing/muppets/scootertop
nbt.display.color=11289369
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/muppets/scootertop
