#
#Fri May 29 13:47:07 EDT 2026
damage=1
texture.leather_layer_1_overlay=textures/clothing/cm/ge_rotr_fo_shirt_m
nbt.display.color=2631736
type=armor
items= minecraft:leather_helmet 
texture.leather_layer_1=textures/clothing/cm/ge_rotr_fo_shirt_m
