damage=1
texture.leather_layer_1_overlay=textures/clothing/hea/jasmine_outfit
nbt.display.color=4181732
type=armor
items= minecraft:leather_boots 
texture.leather_layer_1=textures/clothing/hea/jasmine_outfit
