type=armor
items=minecraft:leather_leggings
nbt.display.color=5914395
texture.leather_layer_2=textures/clothing/hea/russel_pants
texture.leather_layer_2_overlay=textures/clothing/hea/russel_pants
damage=1