#
#Fri May 29 14:16:35 EDT 2026
texture.leather_layer_2_overlay=textures/clothing/sleepingbeauty/aurora_pink_skirt
damage=1
nbt.display.color=16755924
type=armor
items= minecraft:leather_leggings 
texture.leather_layer_2=textures/clothing/sleepingbeauty/aurora_pink_skirt
