type=armor
items=minecraft:leather_leggings
nbt.display.color=2634916
texture.leather_layer_2=textures/clothing/kbf/marcie_shorts
texture.leather_layer_2_overlay=textures/clothing/kbf/marcie_shorts
damage=1