type=armor
items=minecraft:leather_leggings
nbt.display.color=8937013
texture.leather_layer_2=textures/clothing/kbf/pigpen_pants
texture.leather_layer_2_overlay=textures/clothing/kbf/pigpen_pants
damage=1