type=armor
items=minecraft:leather_leggings
nbt.display.color=2503872
texture.leather_layer_2=textures/clothing/kbf/schroeder_shorts
texture.leather_layer_2_overlay=textures/clothing/kbf/schroeder_shorts
damage=1